### ISSUE TITLE
Possible conflict with addon World Quest Tabs

### ISSUE THREAD

**Issue by nancikennedy** [Caerdon/CaerdonWardrobe#11]
11x CaerdonWardrobe\CaerdonWardrobe-v2.9.0.lua:257: attempt to index local 'originalButton' (a nil value)
[string "@CaerdonWardrobe\CaerdonWardrobe-v2.9.0.lua"]:257: in function `SetItemButtonStatus'
[string "@CaerdonWardrobe\CaerdonWardrobe-v2.9.0.lua"]:1057: in function `ClearButton'
[string "@CaerdonWardrobe\external\WorldQuestTab\Core.WorldQuestTab.lua"]:76: in function `UpdateButton'
[string "@CaerdonWardrobe\external\WorldQuestTab\Core.WorldQuestTab.lua"]:12: in function `func'
[string "@WorldQuestTab\Data.lua"]:47: in function `TriggerCallback'
[string "@WorldQuestTab\WorldQuestTab-9.0.05.lua"]:1333: in function `Update'
[string "@WorldQuestTab\WorldQuestTab-9.0.05.lua"]:1513: in function `DisplayQuestList'
[string "@WorldQuestTab\WorldQuestTab-9.0.05.lua"]:1485: in function `UpdateQuestList'
[string "@WorldQuestTab\WorldQuestTab-9.0.05.lua"]:1891: in function `func'
[string "@WorldQuestTab\Data.lua"]:47: in function `TriggerCallback'
[string "@WorldQuestTab\Dataprovider.lua"]:481: in function `Tick'
[string "@WorldQuestTab\Dataprovider.lua"]:443: in function <WorldQuestTab\Dataprovider.lua:443>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
self = CaerdonWardrobe {
 ItemIsSellable = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:659
 SetItemButtonStatus = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:256
 ADDON_LOADED = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1289
 UPDATE_EXPANSION_LEVEL = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1354
 TRANSMOG_COLLECTION_UPDATED = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1346
 0 = <userdata>
 RefreshItems = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1313
 PLAYER_LOGOUT = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1286
 GetTooltipInfo = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:942
 SetItemButtonMogStatusFilter = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:233
 refreshTimer = <table> {
 }
 OnUpdate = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1193
 OnEvent = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1177
 GetBindingStatus = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:48
 AddRotation = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:216
 ProcessItem_Coroutine = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1102
 UpdateButton = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1061
 OnEquipPendingItem = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1339
 RegisterFeature = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:932
 SetItemButtonBindType = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:549
 ClearButton = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1056
 OnContainerFrameUpdateSearchResults = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1326
 waitingToProcess = <table> {
 }
 SetStatusIconPosition = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:176
 OnLoad = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:15
 EQUIPMENT_SETS_CHANGED = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:1350
 ProcessItem = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:669
 timeSinceLastUpdate = 0.076000
}
originalButton = nil
item = nil
feature = nil
locationInfo = nil
options = nil
status = nil
bindingStatus = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'originalButton' (a nil value)"
IsGearSetStatus = <function> defined @CaerdonWardrobe\CaerdonWardrobe.lua:169
ICON_PROMINENT_SIZE = 20
ICON_SIZE_DIFFERENTIAL = 0.800000

**Comment by Caerdon** [comment]
This should be resolved in the latest release.  Please let me know if you're still seeing it!
