### ISSUE TITLE
Support for KkthnxUI

### ISSUE THREAD

**Issue by Kkthnx** [Caerdon/CaerdonWardrobe#12]
Would you be willing to add support for my UI and users? This was brought to my attention by my users that your addon does not work alongside my UI and integrated cargbags. If you are interested, I will be willing to help anyway I can to allow this to happen. Thank you and Happy New Year!

**Comment by Caerdon** [comment]
This has been added in v2.10.0!

**Comment by Kkthnx** [comment]
Thank you <3
