### ISSUE TITLE
Equipment of wrong armour class showing as learnable (on some items)

### ISSUE THREAD

**Issue by Slackluster** [Caerdon/CaerdonWardrobe#15]
On some BoE equipment items, Caerdon shows that the item is learnable by a character when it is not due to armour type restrictions. Below is a sample of green BoE items that I checked on all twelve classes, disabling all other addons to make sure that was not the issue. It seems to be an issue with armour types, as all classes that share the same armour types showed the same behaviour.

Between the items that did and did not behave as expected, I can personally not discern any notable differences. At first I thought it might have to do with shared appearances between items of different armour types, but that did not seem to be the case.

The following items behaved as expected on all twelve classes:
- Consortium Boots (24654)
- Eldr'aan Boots (24670)
- Shadow Council Chain (24661)
- Tranquility Mace (25319)
- Laughing Skull Pants (24610)
- Fireheart Bracers (24596)
- Bogslayer Helm (24954)
- Elite Shoulders (4835)

These Cloth items showed as learnable on Leather, Mail and Plate classes:
- Archmage Bracelets (24684)
- Archmage Slippers (24678)

This Leather item showed as learnable on Mail classes:
- Vengeance Boots (24710)

This Mail item showed as learnable on Leather classes:
- Glorious Shoulders (4833)

These Mail items showed as learnable on Plate classes:
- Soldier's Gauntlets (6547)
- Soldier's Boots (6551)

 These Plate items showed as learnable on Mail classes:
- Warmaul Legplates (24995)
- Bloodscale Legguards (24947)

**Comment by Caerdon** [comment]
Thanks for the detailed report!  I'll definitely dig into this!

**Comment by Slackluster** [comment]
To add to this, lately I've also been seeing the annoying behaviour where the addon doesn't accurately show whether an item's appearance has not been learned at all, or just from that specific itemID.

This is most apparent when comparing it with the information that the Can I Mog It? addon shows. I've been using both simultaneously for a long time because of these discrepancies.

One example:
![image](https://user-images.githubusercontent.com/29845810/170530419-32691aa2-2b51-4ff2-bcac-195824cce435.png)
On the left side here it shows the information from CIMI, which is accurate: one item not learned at all, four items learned but not from those specific items. Whereas Caerdon marks them all as completely unlearned, on the right. (Item IDs 154153, 154148, 154150, 154147, 154152.

**Comment by Caerdon** [comment]
Thanks - I'll take a look at these when I get a chance.  There are some differences between the two that are intentional.  If a piece you know requires a higher level than a piece you could learn, it flags it as learnable, for instance (at least it should if you have completionist mode enabled).

**Comment by Slackluster** [comment]
I see! That is indeed the case for these and possibly the other things I see as well. The ones I have learned require level 50 while the ones I can craft require level 45.

Since the level squish and the introduction of Chromie Time, the level requirements for transmogging gear have been loosened a lot though. Everything pre-Shadowlands is transmoggable from level 10 upwards, as that content is available from level 10 onwards. That is a trend we will continue to see, I expect.

My two other main addons I use to determine new appearances - Can I Mog It? and All The Things do not make that distinction either. ATT only has an option to also consider class-restricted gear.

Is there any chance that could be an option somehow? I'd love to not have to use CIMI anymore and have Caerdon show me the same information ATT does. :D

Edit: Should also note I haven't seen any armour-type mismatches in Caerdon's info in a while, which was what the ticket was originally about. ^^

**Comment by Caerdon** [comment]
I think v2.16.0 should solve these problems.  If you have completionist mode enabled, you'll probably still see it, though, unless it's the exact same item but just different in level (in which case checking the new option will help).  Completionist mode is really only there if you want all the drop sources of an appearance for some reason.  Otherwise, you should be able to leave it off.

**Comment by Slackluster** [comment]
It's looking good so far, thanks for the work! <3
