### ISSUE TITLE
Feature request: support for World Quest List

### ISSUE THREAD

**Issue by Slackluster** [Caerdon/CaerdonWardrobe#17]
The way in which the addon currently works with World Quest Tracker for example is great, and I've been using that addon over World Quests List specifically because I love the way Caerdon integrates with it. I was wondering however if it were possible to also make Caerdon work together with [World Quests List](https://www.curseforge.com/wow/addons/world-quests-list).

I fully understand if it's a no or ends up being a low priority thing, but I'd love to see these two addons work together.

**Comment by Caerdon** [comment]
Basic support for this is added in v2.12.0
