### ISSUE TITLE
Compatibility with WowUp.io ?

### ISSUE THREAD

**Issue by SisterSkaoi** [Caerdon/CaerdonWardrobe#19]
Hi, since WowUp will soon no longer be able to update via curseforge, are you able to push releases here too so that they can be updated through the WowUp client? 
At the moment I can find and manually install the release zip but if I try to load it via the url (https://github.com/Caerdon/CaerdonWardrobe) in the WowUp client it isn't recognised as a valid asset and gives this error:
![image](https://user-images.githubusercontent.com/61105674/162168805-f372379b-9ab3-489f-87ef-de7cbf4dff5d.png)

**Comment by Caerdon** [comment]
As far as I can tell, this is an issue with WowUp itself.  Their guidance indicates that I need to provide tagged releases that include a zip file (which I'm doing).  I looked at their debug logs, and it acts like it's not able to pull the release info, but I can do it manually from the same endpoint.

I'd recommend opening a ticket up on the WowUp side.  If there's something else I need to do, they need to document it better.

**Comment by SisterSkaoi** [comment]
Will do, thank you for looking into it!!

**Comment by SisterSkaoi** [comment]
Okay so it apparently is to do with how you're packaging the release, I think because you're only including the source code rather than a whole addon zipped bundle? In the documentation (https://wowup.io/guide/wowup/hub) they specify "the folder structure of the zip must contain your addon's top level folder(s) at the root."
They normally have 3 assets in the release and it looks like this:
![image](https://user-images.githubusercontent.com/61105674/162646936-1b2e407e-83ce-4617-824c-abb3bd9e6a67.png)
When I raised it with them on the discord (https://discord.gg/rk4F5aD) they agreed that how it was being bundled looked like the issue and suggested if the documentation isn't clear enough you could hop on there and speak to them directly about it.
Thanks again for looking into this, I'm sure it'll make a difference to more than just me to be able to update from here instead of Curse!

**Comment by vandiel01** [comment]
perhaps this might help by adding 'X-Curse-Project-ID' in your TOC so it could be download via WoWUp.

**Comment by Caerdon** [comment]
Adding X-Curse-Project-ID in 2.15.0.  I'll try and take a look shortly and check on those other changes if needed.

**Comment by Barleduq** [comment]
Hi there!  I was trying to download this with Cursebreaker, and when it failed I put in a ticket with them.  This is their answer - perhaps it's a similar problem?  I'm posting here because it wasn't marked closed, and I'm guessing it's similar.
https://github.com/AcidWeb/CurseBreaker/issues/336

**Comment by Caerdon** [comment]
This should be fixed with the latest (v.2.17.0).

**Comment by Barleduq** [comment]
Thank you! Very much appreciated!
-Barleduq
