### ISSUE TITLE
Error when accepting a calling (/quest?)

### ISSUE THREAD

**Issue by Slackluster** [Caerdon/CaerdonWardrobe#21]
1x CaerdonWardrobe\CaerdonWardrobe-v2.16.0.lua:1208: CaerdonWardrobe\features\QuestLog.lua:24: Invalid quest item in SetQuestItem("type", index)
[string "=[C]"]: in function `error'
[string "@CaerdonWardrobe\CaerdonWardrobe-v2.16.0.lua"]:1208: in function <CaerdonWardrobe\CaerdonWardrobe.lua:1201>

Locals:
(*temporary) = "CaerdonWardrobe\features\QuestLog.lua:24: Invalid quest item in SetQuestItem("type", index)"

**Comment by Caerdon** [comment]
I've made some changes in the most recent releases that may have helped here.  I'm not seeing the issue right now, but I'll keep an eye out.  In the meantime, if you can identify any other key details as to when it happens, that could help.  If it's consistent, does it happen if you disable all other addons?

**Comment by Slackluster** [comment]
I'm a little embarrassed to say I didn't try disabling all other addons, I normally always do that before sending in a ticket. I'll keep an eye on it and report back, thanks for the work as always! <3

**Comment by Slackluster** [comment]
I haven't seen the error pop up again, so it seems good for now!
