### ISSUE TITLE
Bug: Mission.lua error

### ISSUE THREAD

**Issue by nancikennedy** [Caerdon/CaerdonWardrobe#26]
In Retail, with CW 3.0.4 and [In Progress Missions](https://www.curseforge.com/wow/addons/ipm) installed, I am getting the following error when I open the [current default] Covenant Sanctum report. It does not matter whether it's by clicking on the minimap button or using a variant of "/script ShowGarrisonLandingPage(2)" to open the window. Loaded separately, neither of them are causing this error.

142x ...nterface/AddOns/CaerdonWardrobe/features/Mission.lua:63: attempt to index local 'elementData' (a number value)
[string "@Interface/AddOns/CaerdonWardrobe/features/Mission.lua"]:63: in function `func'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:109: in function `ForEachFrame'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:508: in function `ForEachFrame'
[string "@Interface/AddOns/CaerdonWardrobe/features/Mission.lua"]:59: in function <...nterface/AddOns/CaerdonWardrobe/features/Mission.lua:57>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:659: in function `Update'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:233: in function `SetScrollPercentageInternal'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:151: in function `FullUpdateInternal'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:631: in function `FullUpdateInternal'
...
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function <Interface/FrameXML/UIParent.lua:3129>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface/FrameXML/GarrisonBaseUtils.lua"]:410: in function <Interface/FrameXML/GarrisonBaseUtils.lua:360>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowGarrisonLandingPage'
[string "@Interface/FrameXML/Minimap.lua"]:896: in function `GarrisonLandingPage_Toggle'
[string "@Interface/FrameXML/Minimap.lua"]:698: in function `ToggleLandingPage'
[string "@Interface/FrameXML/Minimap.lua"]:693: in function <Interface/FrameXML/Minimap.lua:692>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
missionButton = Button {
 EncounterIcon = Frame {
 }
 GetOrderIndex = <function> defined @Interface/SharedXML/Scroll/ScrollBoxListView.lua:77
 MissionTypeBG = Texture {
 }
 BG = Texture {
 }
 CompletedOverlay = Texture {
 }
 ElementDataMatches = <function> defined @Interface/SharedXML/Scroll/ScrollBoxListView.lua:72
 Status = FontString {
 }
 Level = FontString {
 }
 TimeLeft = FontString {
 }
 Reward1 = Frame {
 }
 Reward2 = Frame {
 }
 MissionTypeIcon = Texture {
 }
 Rewards = <table> {
 }
 NumFollowers = FontString {
 }
 SetOrderIndex = <function> defined @Interface/SharedXML/Scroll/ScrollBoxListView.lua:81
 GetElementData = <function> defined @Interface/SharedXML/Scroll/ScrollBoxListView.lua:68
 Title = FontString {
 }
 GetMission = <function> defined @Interface/AddOns/InProgressMissions/InProgressMissions.lua:1049
 0 = <userdata>
 Reward3 = Frame {
 }
 CompletedCheck = Texture {
 }
 MissionType = FontString {
 }
}
elementData = 1
missionIndex = 1
index = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined @Interface/SharedXML/TableUtil.lua:29
(*temporary) = <table> {
 1 = 1
 2 = 2
 3 = 3
 4 = 4
 5 = 5
 6 = 6
 7 = 7
 8 = 8
 9 = 9
 10 = 10
 11 = 11
 12 = 12
 13 = 13
 14 = 14
}
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'elementData' (a number value)"
scrollBox = Frame {
 0 = <userdata>
 SetUpdateLocked = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:123
 OnViewDataChanged = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:604
 GetPanExtentPercentage = <function> defined @Interface/SharedXML/Scroll/ScrollController.lua:74
 GetFrameExtent = <function> defined @Interface/SharedXML/Scroll/ScrollController.lua:11
 GetRightPadding = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:400
 ForEachFrame = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:507
 Rebuild = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:608
 IsUpdateLocked = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:127
 SetLowerShadowAtlas = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:440
 SetFrameExtent = <function> defined @Interface/SharedXML/Scroll/ScrollController.lua:16
 canInterpolateScroll = false
 GetUpperPadding = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:416
 SetShadowsShown = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:448
 GetDerivedScrollRange = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:313
 Interpolate = <function> defined @Interface/SharedXML/Scroll/ScrollController.lua:109
 GetLowerPadding = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:424
 HasDataProvider = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:555
 Update = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:635
 SetScrollPercentage = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:220
 GetExtent = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:252
 GetPanExtent = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:244
 panExtentPercentage = 0.330357
 IsVirtualized = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:571
 Layout = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:166
 Event = <table> {
 }
 SetPanExtentPercentage = <function> defined @Interface/SharedXML/Scroll/ScrollController.lua:78
 SetPanExtent = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:248
 GetScrollPercentage = <function> defined @Interface/SharedXML/Scroll/ScrollController.lua:86
 OnSizeChanged = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:98
 ScrollToOffset = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:338
 OnViewAcquiredFrame = <function> defined @Interface/SharedXML/Scroll/ScrollBox.lua:612
 FindElementDataByPredicate = <func

**Comment by Caerdon** [comment]
I was able to confirm this earlier, but it looks like it may not be occurring with chelatest version of In Progress Missions.  Could you confirm?

**Comment by nancikennedy** [comment]
I can confirm that updating In Progress Missions has resolved this issue.

**Comment by Caerdon** [comment]
Thanks!
