### ISSUE TITLE
Errors on Auction House

### ISSUE THREAD

**Issue by eltreum0** [Caerdon/CaerdonWardrobe#27]
I have been getting a lot of errors whenever i interact with the Auction House, seems to be the frame changed and hasn't been updated

72x ...nterface/AddOns/CaerdonWardrobe/features/Auction.lua:64: attempt to index field 'rowData' (a nil value)
[string "@Interface/AddOns/CaerdonWardrobe/features/Auction.lua"]:64: in function `OnInitializedFrame'
[string "@Interface/AddOns/CaerdonWardrobe/features/Auction.lua"]:26: in function <...nterface/AddOns/CaerdonWardrobe/features/Auction.lua:26>

**Comment by Caerdon** [comment]
I'm unable to reproduce this - the latest version should be fully updated to work with the Auction House.  Does it occur if you only have Caerdon Wardrobe loaded?  Is it caused by doing something specific?

**Comment by eltreum0** [comment]
Loaded and when the auction frame shows

edit here's the full error if it helps:


34x ...nterface/AddOns/CaerdonWardrobe/features/Auction.lua:64: attempt to index field 'rowData' (a nil value)
[string "@Interface/AddOns/CaerdonWardrobe/features/Auction.lua"]:64: in function `OnInitializedFrame'
[string "@Interface/AddOns/CaerdonWardrobe/features/Auction.lua"]:26: in function <...nterface/AddOns/CaerdonWardrobe/features/Auction.lua:26>
[string "@Interface/SharedXML/Scroll/ScrollUtil.lua"]:17: in function <Interface/SharedXML/Scroll/ScrollUtil.lua:16>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:617: in function <Interface/SharedXML/Scroll/ScrollBox.lua:616>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
...
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:225: in function `SignalDataChangeEvent'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:205: in function `SetDataProvider'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:589: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua"]:359: in function <...ard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:333>
[string "=[C]"]: in function `RefreshScrollFrame'
[string "@Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua"]:242: in function `Reset'
[string "@Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseBrowseResultsFrame.lua"]:136: in function `UpdateBrowseResults'
[string "@Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseBrowseResultsFrame.lua"]:77: in function <...nHouseUI/Blizzard_AuctionHouseBrowseResultsFrame.lua:75>

Locals:
self = <table> {
 OnSelectBrowseResult = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:253
 OnSetPostItem = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:278
 GetDisplayInfoInternal = <function> defined @Interface/AddOns/CaerdonWardrobe/FeatureMixin.lua:32
 GetTooltipData = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:89
 OnClearPostItem = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:317
 OnUpdate = <function> defined @Interface/AddOns/CaerdonWardrobe/FeatureMixin.lua:74
 Init = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:8
 Refresh = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:99
 OnAllAuctionsInitializedFrame = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:33
 AUCTION_HOUSE_SHOW = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:22
 OnSetAuctionItemDisplay = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:128
 shouldHookAuction = false
 auctionContinuableContainer = <table> {
 }
 OnInitializedFrame = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:58
 IsSameItem = <function> defined @Interface/AddOns/CaerdonWardrobe/FeatureMixin.lua:24
 GetName = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:3
 GetDisplayInfo = <function> defined @Interface/AddOns/CaerdonWardrobe/features/Auction.lua:105
}
auctionFrame = Frame {
 0 = <userdata>
 SetHighlightCallback = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:118
 tableBuilder = <table> {
 }
 isInitialized = true
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 SetLineOnLeaveCallback = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:199
 SetDataProvider = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:72
 GetScrollBoxDataIndexBegin = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:297
 SetState = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:245
 RightEdge = Texture {
 }
 OnEnterListLine = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:193
 OnShow = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:224
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 state = 4
 RefreshScrollFrame = <function> defined =[C]:-1
 ScrollBar = Frame {
 }
 SetSelectedEntryByCondition = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:271
 lineOnLeaveCallback = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseUtil.lua:574
 lineTemplate = "AuctionHouseFavoritableLineTemplate"
 PixelSnapDisabled = true
 SetRefreshCallback = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:100
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 hideRefreshFrame = true
 SpinnerAnim = AnimationGroup {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 NineSlice = Frame {
 }
 OnLoad = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:57
 TopEdge = Texture {
 }
 GetHeaderContainer = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:376
 UpdateTableBuilderLayout = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseItemList.lua:104
 getEntry = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseBrowseResultsFrame.lua:49
 lineOnEnterCallback = <function> defined @Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseUtil.lua:560
 BottomRightCorner = Texture {
 }
 OnScrollBoxScroll = <function> defined @Interface/Ad

**Comment by eltreum0** [comment]
to add more into it, i've noticed it only errors on some characters where i have added transmog items to my favorite list

**Comment by Caerdon** [comment]
Tried to add some transmog items to my favorite list but couldn't seem to get anything that could trigger.  I've added some code to try and avoid the error if it gets in that state.  The change will be in 3.0.5.

**Comment by eltreum0** [comment]
Checking for nil seems to have fixed it ty
