### ISSUE TITLE
Showing Learnable Icon on piece not transmogable by toon

### ISSUE THREAD

**Issue by Hyphie24** [Caerdon/CaerdonWardrobe#30]
Showing the unlearned appearance icon on a piece of mail gear on a plate wearer. I don't know if it's a manual change or just somehow it's linked to a plate piece. On version 3.0.6

![icon bug](https://user-images.githubusercontent.com/31455641/200131441-7389dbe2-d96f-4d27-a48d-1a9b88c66fab.png)

**Comment by Caerdon** [comment]
Thanks - I found another example to repro this with, so I'll dig into it shortly.

**Comment by Caerdon** [comment]
This should be fixed in v3.0.7.
