### ISSUE TITLE
Got chat message: "Tooltip processing needed"

### ISSUE THREAD

**Issue by LyaVanLou** [Caerdon/CaerdonWardrobe#32]
Got the following when looting Timeless Coin:

![image](https://user-images.githubusercontent.com/56847157/202605266-68154a89-de52-442c-bb47-ebd4974508b8.png)

On that note - it would be superb if chat messages would have an indicator of which addon posted it. <3

**Comment by Caerdon** [comment]
This should be fixed in v3.3.0, and I've fixed a few chat messages that could show up to indicate it's Caerdon doing it.  :)  (Probably still have more to do here but grabbed the primary culprits).
