### ISSUE TITLE
Suggestion: do not use RegisterVerticalLayoutCategory

### ISSUE THREAD

**Issue by Slackluster** [Caerdon/CaerdonWardrobe#36]
I was recently looking into the UI Taint issues a lot of players are running into. It reminded me that Wowpedia has a warning about using the in 10.0 added Vertical Layout:

![image](https://user-images.githubusercontent.com/29845810/235301902-e50d4439-8690-4ea0-9d01-87bc6a9d709b.png)
Source: https://wowpedia.fandom.com/wiki/Patch_10.0.0/API_changes

Now CaerdonWardrobe happened to be the only AddOn I have that uses this, so I've disabled it for the past few days along with !!NoTaint2 which has been a great help in preventing these taint issues, to see if this would prevent the taint issues from appearing.

Now these past few days I've yet to run into any taint issues. This of course is not complete proof the Vertical Layout is actually causing this taint, but since it also seems to be heavily recommended to not use it, that might also be a direction this AddOn can take. :)

**Comment by Caerdon** [comment]
I'm not using RegisterVerticalLayoutCategory right now for that very reason.  I have a file in that has it, but the file isn't actually included in the addon that's loaded by WoW.
