### ISSUE TITLE
Bug: ProfessionsFrame error

### ISSUE THREAD

**Issue by nancikennedy** [Caerdon/CaerdonWardrobe#39]
On Retail, 10.1.7, using CW v3.4.2...this happens when 1st logging in on a character . I recall another addon having this kind of error in 10.1.5, and I believe it had to do with the addon doing this type of call before professions registered or something like that. I can't remember the name of the other addon that was having this problem.

2x ...rfaceCaerdonWardrobe/features/TradeSkill.lua:17: attempt to index global 'ProfessionsFrame' (a nil value)
[string "@CaerdonWardrobe/features/TradeSkill.lua"]:17: in function `handler'
[string "@CaerdonWardrobe/CaerdonWardrobe.lua"]:861: in function <CaerdonWardrobe/CaerdonWardrobe.lua:852>
[string "=[C]"]: in function `OpenTradeSkill'
[string "@Molinari/hack.lua"]:61: in function <Molinari/hack.lua:54>

Locals:
self = <table> {
 Init = <function> defined @CaerdonWardrobe/features/TradeSkill.lua:10
 OnSchematicFormInit = <function> defined @CaerdonWardrobe/features/TradeSkill.lua:60
 Refresh = <function> defined @CaerdonWardrobe/features/TradeSkill.lua:84
 GetName = <function> defined @CaerdonWardrobe/features/TradeSkill.lua:6
 GetTooltipData = <function> defined @CaerdonWardrobe/features/TradeSkill.lua:80
 isHooked = true
 OnInitializedFrame = <function> defined @CaerdonWardrobe/features/TradeSkill.lua:23
 TRADE_SKILL_SHOW = <function> defined @CaerdonWardrobe/features/TradeSkill.lua:14
 GetDisplayInfoInternal = <function> defined @CaerdonWardrobe/FeatureMixin.lua:32
 IsSameItem = <function> defined @CaerdonWardrobe/FeatureMixin.lua:24
 OnUpdate = <function> defined @CaerdonWardrobe/FeatureMixin.lua:78
 GetDisplayInfo = <function> defined @CaerdonWardrobe/features/TradeSkill.lua:87
}
name = nil
(*temporary) = <function> defined @SharedXML/Scroll/ScrollUtil.lua:38
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ProfessionsFrame' (a nil value)"

**Comment by Caerdon** [comment]
Looks like the same issue CanIMogIt was having here: https://github.com/p3lim-wow/Molinari/issues/111

I've identified the fix and will land it shortly!

**Comment by Caerdon** [comment]
Fixed in v3.4.3!
