### ISSUE TITLE
from Latest Git

### ISSUE THREAD

**Issue by vandiel01** [Caerdon/CaerdonWardrobe#4]
Happens when you take/abandon almost ANY quest

`3x CaerdonWardrobe\Core.lua:2011: attempt to call field 'GetSelectedQuest' (a nil value)
[string "@CaerdonWardrobe\Core.lua"]:2011: in function <CaerdonWardrobe\Core.lua:2009>
[string "@CaerdonWardrobe\Core.lua"]:2021: in function <CaerdonWardrobe\Core.lua:2017>
[string "@CaerdonWardrobe\Core.lua"]:2126: in function <CaerdonWardrobe\Core.lua:2121>
[string "=[C]"]: in function `QuestInfo_Display'
[string "@FrameXML\QuestMapFrame.lua"]:505: in function `QuestMapFrame_ShowQuestDetails'
[string "@FrameXML\QuestMapFrame.lua"]:631: in function `QuestMapFrame_OpenToQuestDetails'
[string "@Blizzard_ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua"]:84: in function `OnBlockHeaderClick'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:535: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:533>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'GetSelectedQuest' (a nil value)"`

**Comment by Caerdon** [comment]
I believe this issue is resolved in v2.5.0 but let me know if you're still seeing it.
