### ISSUE TITLE
Item Info 

### ISSUE THREAD

**Issue by brunolfurimmer** [Caerdon/CaerdonWardrobe#40]
Hi there,
Is there anyway to disable the additional information from CW shown in the item info frame? It is causing my game to freeze everytime I aquire a new item or so. I'm not sure if it is designed to be a new feature?

Thanks

![WoWScrnShot_092423_182413](https://github.com/Caerdon/CaerdonWardrobe/assets/82733077/8778d128-9897-4a34-b69f-acd0b9e10b0a)

**Comment by Caerdon** [comment]
There's a Debug checkbox in settings in the upper right that should disable this when it's unchecked.  I'll have to review my default settings to confirm Debug isn't on by default (it shouldn't be).

**Comment by brunolfurimmer** [comment]
Thank you so much! That works!
