### ISSUE TITLE
Error when using adventure journal item set search

### ISSUE THREAD

**Issue by Slackluster** [Caerdon/CaerdonWardrobe#41]
![image](https://github.com/Caerdon/CaerdonWardrobe/assets/29845810/d7a0ae4c-ef57-40f5-8cdd-fc402ea3603d)

5x CaerdonWardrobe/features/EncounterJournal.lua:165: attempt to index field 'searchPreview' (a nil value)
[string "@CaerdonWardrobe/features/EncounterJournal.lua"]:165: in function `OnEncounterJournalUpdateSearchPreview'
[string "@CaerdonWardrobe/features/EncounterJournal.lua"]:20: in function <CaerdonWardrobe/features/EncounterJournal.lua:20>
[string "=[C]"]: in function `EncounterJournal_UpdateSearchPreview'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:2280: in function `EncounterJournal_ShowSearch'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:2289: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:2287>

Locals:
self = <table> {
 OnSearchResultsScrollBoxRangeChanged = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:51
 UpdateScrollBox = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:25
 ADDON_LOADED = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:14
 Init = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:10
 OnEncounterJournalUpdateSearchPreview = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:152
 Refresh = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:74
 GetName = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:6
 PLAYER_LOOT_SPEC_UPDATED = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:55
 GetTooltipData = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:59
 OnEJSuggestFrame_UpdateRewards = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:103
 OnConfigureItemButton = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:133
 OnLootContainerScrollBoxRangeChanged = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:47
 GetDisplayInfoInternal = <function> defined @CaerdonWardrobe/FeatureMixin.lua:32
 IsSameItem = <function> defined @CaerdonWardrobe/FeatureMixin.lua:24
 OnUpdate = <function> defined @CaerdonWardrobe/FeatureMixin.lua:78
 GetDisplayInfo = <function> defined @CaerdonWardrobe/features/EncounterJournal.lua:80
}
numResults = 71
lastShown = EncounterJournalSearchBox {
 0 = <userdata>
 minCharacters = 3
 OnFocusGained = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3268
 Right = Texture {
 }
 Left = Texture {
 }
 searchIcon = EncounterJournalSearchBoxSearchIcon {
 }
 OnTextChanged = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3123
 IsCurrentTextValidForSearch = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3115
 OnKeyDown = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3255
 searchPreviewUpdateDelay = 0
 Middle = Texture {
 }
 SetSearchResultsFrame = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3107
 Clear = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3099
 OnShow = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3111
 buttonTemplate = "EncounterSearchSMTemplate"
 clearButton = EncounterJournalSearchBoxClearButton {
 }
 IsTextValidForSearch = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3119
 IsSearchPreviewShown = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3103
 GetSearchButtonCount = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3145
 OnFocusLost = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3263
 FixSearchPreviewBottomBorder = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3178
 searchResultsFrame = EncounterJournalSearchResults {
 }
 selectedIndex = 1
 HasStickyFocus = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3072
 searchProgress = EncounterJournalSearchBoxSearchProgress {
 }
 searchPreviewContainer = Frame {
 }
 allResultsIndex = 6
 showAllResults = Button {
 }
 SetSearchPreviewSelection = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3200
 searchButtons = <table> {
 }
 HideSearchPreview = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3078
 SetSearchPreviewSelectionToAllResults = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3234
 UpdateSearchPreview = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3149
 Close = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3094
 GetButtons = <function> defined @SharedXML/SharedUIPanelTemplates.lua:3137
 GetAllRes

**Comment by Caerdon** [comment]
This is resolved in the latest release (and I added support for showing icons on the item sets themselves).
