### ISSUE TITLE
Lua error when hovering over items

### ISSUE THREAD

**Issue by Slackluster** [Caerdon/CaerdonWardrobe#42]
Happens on vendors, especially.

2x CaerdonWardrobe/CaerdonWardrobe.lua:884: CaerdonWardrobe/CaerdonItem.lua:138: bad argument #1 to 'IsItemDataCached' (Usage: local isCached = C_Item.IsItemDataCached(itemLocation))
[string "=[C]"]: in function `error'
[string "@CaerdonWardrobe/CaerdonWardrobe.lua"]:884: in function <CaerdonWardrobe/CaerdonWardrobe.lua:877>

Locals:
(*temporary) = "CaerdonWardrobe/CaerdonItem.lua:138: bad argument #1 to 'IsItemDataCached' (Usage: local isCached = C_Item.IsItemDataCached(itemLocation))"

**Comment by Caerdon** [comment]
I fixed this in a follow up release.  Please pull down the latest release and see if it resolves it!

**Comment by Slackluster** [comment]
Just confirming I've not seen the issue anymore after updating, thanks!
