### ISSUE TITLE
Icon not showing in loot window & Vendor Error

### ISSUE THREAD

**Issue by Hyphie24** [Caerdon/CaerdonWardrobe#43]
Possibly caused from item data changes done in v3.5.

Using v3.6.2

![image](https://github.com/Caerdon/CaerdonWardrobe/assets/31455641/d387d9f9-addd-45cc-9969-6b1431118a0f)

also getting this error when buying items from vendor

4x CaerdonWardrobe/CaerdonWardrobe.lua:899: CaerdonWardrobe/types/RecipeMixin.lua:284: bad argument #1 to 'gsub' (string expected, got nil)
[string "=[C]"]: in function `error'
[string "@CaerdonWardrobe/CaerdonWardrobe.lua"]:899: in function <CaerdonWardrobe/CaerdonWardrobe.lua:892>

Locals:
(*temporary) = "CaerdonWardrobe/types/RecipeMixin.lua:284: bad argument #1 to 'gsub' (string expected, got nil)"

**Comment by Caerdon** [comment]
This should be fixed in 3.6.3.  I couldn't directly reproduce the recipe error, but I made it a bit more robust, as well.  If you still see something here or are missing icons you think you shouldn't be, let me know the vendor.
