### ISSUE TITLE
attempt to index field 'Modules' (a nil value)

### ISSUE THREAD

**Issue by Quartzfire** [Caerdon/CaerdonWardrobe#48]
Good Evening,

I initially logged a ticket against AngrierWorldQuests, and the author has come back to me with:

"The bug is in CaerdonWardrobe, it has an integration to Angrier World Quests, but hasn't been updated to the new, rewrite version.
Please report a bug report with the here instead 🙂"

Ref: https://github.com/GurliGebis/WoWAddon-AngrierWorldQuests/issues/76

So here I am ... 

I get the following LUA during loading of the game.

4x ...ernal/AngrierWorldQuests/Core.AngrierWorldQuests.lua:15: attempt to index field 'Modules' (a nil value)
[string "@CaerdonWardrobe/external/AngrierWorldQuests/Core.AngrierWorldQuests.lua"]:15: in function Init' [string "@CaerdonWardrobe/CaerdonWardrobe.lua"]:1060: in function handler'
[string "@CaerdonWardrobe/CaerdonWardrobe.lua"]:1005: in function <CaerdonWardrobe/CaerdonWardrobe.lua:1002>

Locals:
self =

{
}
addon =
{
modules =
{
}
defaultModuleLibraries =
{
}
enabledState = true
baseName = "AngrierWorldQuests"
Version = "11.0.2-20240910-2"
Name = "Angrier World Quests"
defaultModuleState = true
name = "AngrierWorldQuests"
orderedModules =
{
}
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Modules' (a nil value)"
addonName = "AngrierWorldQuests"
isHooked = false

**Comment by GurliGebis** [comment]
To add some info 🙂
I have rewritten and reworked large parts of the addon.

Things have moved into Ace3 Addon modules.
Please reach out if you have any questions.

**Comment by Caerdon** [comment]
Thanks for the report - this is fixed in v3.9.0 (releasing shortly).

**Comment by Quartzfire** [comment]
Awesome, thanks very much for your quick response.
