### ISSUE TITLE
SL 9.0.2 hook function problem

### ISSUE THREAD

**Issue by yoshimo** [Caerdon/CaerdonWardrobe#7]
Date: 2020-09-28 09:06:49
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\CaerdonWardrobeBagnon\Core.Bagnon.lua line 103:
   Usage: hooksecurefunc([table,] "function", hookfunc)
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "@CaerdonWardrobeBagnon\Core.Bagnon.lua"]:103: HookBagnon()
   [string "@CaerdonWardrobeBagnon\Core.Bagnon.lua"]:113: in main chunk
Locals:

**Comment by Caerdon** [comment]
Caerdon Wardrobe has Bagnon support built-in and no longer requires the CaerdonWardrobeBagnon addon (hasn't for a few years), so I removed some functionality that was apparently still letting it work during recent cleanup.  If you uninstall the CaerdonWardrobeBagnon addon, you should be good to go here.
